# fly.toml app configuration file generated for github-playright on 2023-11-14T16:32:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "github-playright"
primary_region = "otp"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
